# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bvUU9jYN2buxxs0T8oHgkMW9Mv3lng9J
"""

from flask import Flask, render_template
import yfinance as yf
import pandas as pd
import plotly.graph_objects as go
import plotly.io as pio

app = Flask(__name__)

@app.route("/")
def index():
    # Fetch stock data
    df = yf.download('EA', start='2015-01-01', end='2023-12-31').reset_index()

    # Create Plotly chart
    fig = go.Figure()
    fig.add_trace(go.Scatter(x=df['Date'], y=df['Close'], mode='lines', name='EA Stock'))
    fig.update_layout(title="EA Stock Price (2015–2023)",
                      paper_bgcolor='rgba(13,17,23,1)',
                      plot_bgcolor='rgba(13,17,23,1)',
                      font=dict(color='white'))

    # Convert Plotly figure to HTML
    plot_html = pio.to_html(fig, full_html=False, include_plotlyjs='cdn')

    # Metrics
    current_price = df['Close'].iloc[-1]
    growth = ((df['Close'].iloc[-1] - df['Close'].iloc[0]) / df['Close'].iloc[0]) * 100
    best_year = df.loc[df['Close'].idxmax()]['Date'].year
    worst_year = df.loc[df['Close'].idxmin()]['Date'].year

    return render_template("index.html",
                           current_price=round(current_price, 2),
                           growth=round(growth, 2),
                           best_year=best_year,
                           worst_year=worst_year,
                           plot_html=plot_html)

